import { test, expect, type Page } from "@playwright/test";
import { join } from "path";

// ---- assets -----------------------------------------------------------------
// The current UI is built around the hymn demo + file uploads. The deterministic
// synthetic pair still lives in public/ (regenerated by global-setup) and is the
// reliable way to assert exact note-level counts, so these tests drive it via
// the file inputs rather than demo buttons.

const ROOT = join(__dirname, "..");
const SAMPLE_XML = join(ROOT, "public", "sample.musicxml");           // 16-note C scale, tempo 100
const SAMPLE_MID = join(ROOT, "public", "sample-performance.mid");    // same scale: 1 wrong + 1 missed + 1 late
const PERFECT_MID = join(__dirname, "fixtures", "perfect-perf.mid");  // same scale, no errors

// ---- locators ---------------------------------------------------------------
// Two file inputs contain ".musicxml" in their accept list (the dedicated XML
// upload and the PDF/MXL/photo upload), so match the dedicated one exactly.
const scoreXmlInput = (page: Page) => page.locator('input[accept=".musicxml,.xml"]');
const midiInput = (page: Page) => page.locator('input[accept=".mid,.midi"]');

// ---- helpers ----------------------------------------------------------------
async function loadSampleScore(page: Page) {
  await scoreXmlInput(page).setInputFiles(SAMPLE_XML);
  await expect(page.getByTestId("status")).toContainText("Loaded score");
  await expect(page.getByTestId("status")).toContainText("16 notes");
}

async function waitForScoreSvg(page: Page) {
  // OSMD renders into the score-view container; wait for the SVG to appear.
  await expect(
    page.getByTestId("score-view").locator("svg").first()
  ).toBeVisible({ timeout: 15_000 });
}

// ---- suite ------------------------------------------------------------------

test.describe("FSA pipeline", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/");
  });

  // --------------------------------------------------------------------------
  test("page loads with correct title and all sections present", async ({ page }) => {
    await expect(page).toHaveTitle(/Music Coach/);
    await expect(page.getByRole("heading", { level: 1 })).toContainText("Music Coach");
    await expect(page.getByTestId("score-view")).toBeVisible();
    await expect(page.getByTestId("piano-keyboard")).toBeVisible();
    await expect(page.getByTestId("status")).toBeVisible();
  });

  // --------------------------------------------------------------------------
  test.describe("Score input", () => {
    test("MusicXML path: parse 16 notes at tempo 100, render to SVG", async ({ page }) => {
      await loadSampleScore(page);
      // Tempo is shown in the Score section heading, not the status line.
      await expect(page.getByRole("heading", { name: /Score/ })).toContainText("100 BPM");
      await waitForScoreSvg(page);
    });

    test("keyboard shows reference pitches after score load", async ({ page }) => {
      await loadSampleScore(page);
      const keyboard = page.getByTestId("piano-keyboard");
      await expect(keyboard).toBeVisible();
      // The keyboard renders one div per key.
      await expect(keyboard.locator("div")).not.toHaveCount(0);
    });
  });

  // --------------------------------------------------------------------------
  // MIDI upload removed from UI — tests kept for reference, skipped until replaced with audio path.
  test.describe.skip("Performance comparison — MIDI path", () => {
    test.beforeEach(async ({ page }) => {
      await loadSampleScore(page);
      await midiInput(page).setInputFiles(SAMPLE_MID);
      await expect(page.getByTestId("status")).toContainText("Loaded performance");
    });

    test("Compare button enabled after both inputs loaded", async ({ page }) => {
      await expect(page.getByRole("button", { name: "Compare" })).toBeEnabled();
    });

    test("comparison produces correct counts", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const summary = page.getByTestId("results-summary");
      await expect(summary).toContainText("87.5%");
      await expect(summary).toContainText("match: 14");
      await expect(summary).toContainText("wrong: 1");
      await expect(summary).toContainText("missed: 1");
      await expect(summary).toContainText("extra: 0");
      await expect(summary).toContainText("late: 1");
      await expect(summary).toContainText("early: 0");
    });

    test("alignment table: 16 rows (14 match + 1 wrong + 1 missed)", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const rows = page.getByTestId("alignment-table").locator("tbody tr");
      await expect(rows).toHaveCount(16);
    });

    test("wrong note: E4 expected, D#4 played", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const wrongRows = page.getByTestId("alignment-table").locator("tbody tr").filter({ hasText: "wrong" });
      await expect(wrongRows).toHaveCount(1);
      await expect(wrongRows).toContainText("E4");   // expected
      await expect(wrongRows).toContainText("D#4");  // played
    });

    test("missed note: A4 in the expected column", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const missedRows = page.getByTestId("alignment-table").locator("tbody tr").filter({ hasText: "missed" });
      await expect(missedRows).toHaveCount(1);
      await expect(missedRows).toContainText("A4");
    });

    test("late note: exactly one timing=late in a match row", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const lateRows = page.getByTestId("alignment-table").locator("tbody tr").filter({ hasText: "late" });
      await expect(lateRows).toHaveCount(1);
      // The late row must be a "match" row (timing annotates a matched note).
      await expect(lateRows).toContainText("match");
    });

    test("feedback section is rendered", async ({ page }) => {
      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      // The deterministic feedback list always leads with the pitch-accuracy line.
      await expect(
        page.locator("ul li").filter({ hasText: "Pitch accuracy:" }).first()
      ).toBeVisible();
    });
  });

  // --------------------------------------------------------------------------
  test.describe.skip("Performance comparison — perfect MIDI", () => {
    test("perfect performance → 100% accuracy, all match", async ({ page }) => {
      await loadSampleScore(page);
      await midiInput(page).setInputFiles(PERFECT_MID);
      await expect(page.getByTestId("status")).toContainText("Loaded performance");

      await page.getByRole("button", { name: "Compare" }).click();
      await expect(page.getByTestId("status")).toContainText("Comparison complete");

      const summary = page.getByTestId("results-summary");
      await expect(summary).toContainText("100.0%");
      await expect(summary).toContainText("match: 16");
      await expect(summary).toContainText("wrong: 0");
      await expect(summary).toContainText("missed: 0");

      const rows = page.getByTestId("alignment-table").locator("tbody tr");
      await expect(rows).toHaveCount(16);
    });
  });
});
